### ISSUE TITLE
Notification displaying error even though sending email actually succeeded

### ISSUE THREAD

**Issue by rgh36167** [grote/BlitzMail#13]
This happens after the latest update from f-droid.

I have notifications for sent email enabled - when the email is sent it shows an error and a menu send again/dismiss etc. 

As a feature wish.. an option to have the email sent notification transient, disappear without further user action after eg 1 minute.

**Comment by grote** [comment]
I guess you are using 0.6-beta2?

**Comment by rgh36167** [comment]
yes

**Comment by grote** [comment]
The fix is now out in the latest 0.6-rc1 release. Can you please confirm it's fixed?
If you noticed other issues with this release, please report them!

**Comment by rgh36167** [comment]
this woks fine, however other issues turned that may be related.

**Comment by grote** [comment]
Thanks for testing. Please create new tickets for the other issues.
