### ISSUE TITLE
retrying mail sending does not seem to work

### ISSUE THREAD

**Issue by rgh36167** [grote/BlitzMail#17]
Tried to email a few pictures in short succession while in airplane mode which failed with the message can't contact smtp server.

Disabled airplane mode and waited for a minute to see if it would retry automatically - it did not.

Hit try again in the notification - it is displaying "sending please wait" with the progress bar since 2 hours and nothing is sent.

**Comment by grote** [comment]
"Try again" should try sending again right away and should fail while in airplane mode. Only if you click "Send later" the emails should be send out later when you leave airplane mode.

**Comment by rgh36167** [comment]
I did first disable airplane mode, then wait a minute without doing anything and hit "try again" after this. So it was with a working network connection when I retried.

Did not try "Send later" yet.

**Comment by rgh36167** [comment]
weird, there were several notifications of this type left and when I did "try again" for some of those other notifications it is sending the emails as expected. 

Not sure why the first one seemed to be hanging forever.

**Comment by grote** [comment]
> Not sure why the first one seemed to be hanging forever.

Let me know when you can reproduce this behavior reliably and let me know how.

**Comment by rgh36167** [comment]
what I can reproduce reliably is a huge mess. 

I hit those 5 notifications and select "try again". It emails me 5 times the same file instead of the 5 file originally selected. 

Will try to reproduce the original error with a single file but this might be a separate bug.

**Comment by rgh36167** [comment]
In addition when invoking blitzmail directly it says there are 6 emails waiting to be sent.

So one bus is that the notifications don't match failed/delayed mails.

**Comment by rgh36167** [comment]
can not reproduce the original error now. Can you reproduce the other condition - that 6 identical files are sent instead of those originally selected?

I won't be available for some days or maybe 2 weeks for testing.

**Comment by rgh36167** [comment]
the original error may be a timeout caused by a slow network connection which Blitzmail fails to detect. OS monitor did not display any open connections from Blitzmail anymore while Blitzmail notification still showed work in progress.

It does not help that when many files are emailed in close succession they are sent in parallel, killing the slow connection.

**Comment by grote** [comment]
I could not reproduce the issue with 6 identical files being sent. Also, you raised many different issues here and none of them reproducible.

Could you please find some steps of what to do to reproduce one single issue and then create one single ticket for this issue? If you find other issues, please create separate tickets for them.

Thanks!
