### ISSUE TITLE
mailing from "Downloads" fails, permission error

### ISSUE THREAD

**Issue by rgh36167** [grote/BlitzMail#19]
"permission Denial: reading com.android.providers.downloads.DownloadStorageProvider ...."

happens when "sharing" from builtin "Downloads" app 5.0.2-1 on a Moto G, 1. gen.. OS Monitor calls it "android.process.media"

**Comment by grote** [comment]
This seems to be the problem described here: https://stackoverflow.com/questions/19837358/android-kitkat-securityexception-when-trying-to-read-from-mediastore
