### ISSUE TITLE
set subject when sharing links

### ISSUE THREAD

**Issue by ghost** [grote/BlitzMail#23]
When sharing links from Firefox via longpress menu the subject of the generated email is empty. Should inlcude the link text if known and/or url.

**Comment by grote** [comment]
It looks like the only information that Firefox is relaying is the URL itself as text. The only thing I could do is to also show the URL (or the beginning of it) in the email subject.

**Comment by rgh36167** [comment]
Same here, the URL seems like the only piece of information available. You could strip https{0,1}://www.  away and url.decode it (things like %3D) .

**Comment by ducalex** [comment]
This should be fixed by e3dc52fd.
