### ISSUE TITLE
How do I retrieve or write an new Email?

### ISSUE THREAD

**Issue by markuskramerIgitt** [grote/BlitzMail#29]
I installed BlitzMail from F-Droid.

I opened BlitzMail, and got a [screen with title bar "<- BlitzMail"](https://github.com/grote/BlitzMail/blob/master/artwork/screen_MainActivity.png) where I entered all configuration (Sending, Mail Server Settings, Interface).

I see only one menu item: the backward key on the title bar, which closes BlitzMail.
How do I retrieve or write an new Email?

**Comment by guest4711** [comment]
Blitzmail is for sending mails, not for retrieving...
It registers as a handler for the share menu, so you could send any file via "share -- blitzmail". You may also use blitznote to send a note...
Cheers! guest4711

Am 9. Juni 2017 09:50:32 MESZ schrieb Markus <notifications@github.com>:

**Comment by grote** [comment]
Thanks for explaining @guest4711! I guess this closes this ticket.

**Comment by markuskramerIgitt** [comment]
Thank you, @guest4711!
