### ISSUE TITLE
Issue When Used With Tasker

### ISSUE THREAD

**Issue by Zweihander-Main** [grote/BlitzMail#30]
When I tried to setup a [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm&hl=en) 'Compose Email' task, BlitzMail was failing where other e-mail applications (K-9 for example) were not. 

The task was to send an email with a bit of text for the subject and body and nothing else (so no attachments). When the task executed, BlitzMail would crash and I would be prompted to re-open it. However irregardless of if I did reopen it or not, a 'Sending BlitzMail' notification would appear. The email is never sent and the notification does not disappear (running the task again adds another similar notification). 

Logcat:
```
10-20 00:09:39.945 I/ActivityManager(505): START u0 {act=android.intent.action.SEND typ=message/rfc822 flg=0x30000005 cmp=de.grobox.blitzmail/.SendActivity clip={message/rfc822 T:Testbshssbhs shshshshs shsjsjsjsjs
10-20 00:09:40.008 I/ActivityManager(505): Start proc 15950:de.grobox.blitzmail/u0a115 for activity de.grobox.blitzmail/.SendActivity
10-20 00:09:40.144 W/System  (15950): ClassLoader referenced unknown path: /data/app/de.grobox.blitzmail-1/lib/arm
10-20 00:09:40.256 E/AndroidRuntime(15950): Process: de.grobox.blitzmail, PID: 15950
10-20 00:09:40.256 E/AndroidRuntime(15950): java.lang.RuntimeException: Unable to start activity ComponentInfo{de.grobox.blitzmail/de.grobox.blitzmail.SendActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
10-20 00:09:40.256 E/AndroidRuntime(15950): 	at de.grobox.blitzmail.SendActivity.getMailWithAttachments(SendActivity.java:266)
10-20 00:09:40.256 E/AndroidRuntime(15950): 	at de.grobox.blitzmail.SendActivity.handleSendAttachment(SendActivity.java:233)
10-20 00:09:40.256 E/AndroidRuntime(15950): 	at de.grobox.blitzmail.SendActivity.onCreate(SendActivity.java:117)
10-20 00:09:40.262 W/ActivityManager(505):   Force finishing activity de.grobox.blitzmail/.SendActivity
10-20 00:09:40.276 W/ActivityManager(505):   Force finishing activity de.grobox.blitzmail/.SendActivity
10-20 00:09:40.276 W/ActivityManager(505): Duplicate finish request for ActivityRecord{4730dac u0 de.grobox.blitzmail/.SendActivity t3153 f}
10-20 00:09:40.776 W/ActivityManager(505): Activity pause timeout for ActivityRecord{4730dac u0 de.grobox.blitzmail/.SendActivity t3153 f}
10-20 00:09:41.517 W/ActivityManager(505):   Force finishing activity de.grobox.blitzmail/.SendActivity
10-20 00:09:41.518 I/ActivityManager(505): Killing 15950:de.grobox.blitzmail/u0a115 (adj 900): crash
```
Running Android 7.1.2 (LineageOS)

I got a workaround working by creating a custom Intent task in Tasker and using `text/plain` as the MIME type - the email sends as expected using this method. If I change the MIME type to anything besides 'text/plain', it crashes in a similar manner to before so I suspect that might have something to do with it. 

If this sounds like it's more on Tasker's end, feel free to close the issue and I can ping the developer. 

For anyone stumbling upon this with a similar problem, the solution I found was:
`A1: Send Intent [ Action:android.intent.action.SEND Cat:Default Mime Type:text/plain Data: Extra:android.intent.extra.SUBJECT:Test Extra:android.intent.extra.TEXT:Test Extra: Package: Class: Target:Activity ] `

**Comment by grote** [comment]
Tasker seems to be non-free software, so somebody else would need to debug and fix this. It would help to know what Tasker is trying to do. Not really obvious from the stack trace.

**Comment by Zweihander-Main** [comment]
Closing as no longer applicable -- `Compose Email` task appears to have changed in recent versions of Tasker such that the `Send Intent` option above is the only option to accomplish this (and it still works well with BlitzMail).
