### ISSUE TITLE
Mails with missing attachments stay around forever

### ISSUE THREAD

**Issue by guest4711** [grote/BlitzMail#32]
Blitzmail shows me that two mails are waiting to be send. But I see no chance to inspect their contents nor to delete them. So they stay here until forever (or until I delete data of BlitzMail).

I noticed the waiting mails after an upgrade cause blitzmail told me it could not find the ![attachments.]

**Comment by grote** [comment]
Can you get me a logcat trace when it tries to send the mail and fails? What exactly is the error message? Maybe do a screenshot.

Does the mails go away when you select `Dismiss` in the notification?

**Comment by guest4711** [comment]
Here's the screenshot as requested..

**Comment by guest4711** [comment]
@grote Thanks, I did add it to my email when replying but its been stripped off. Now it's on imgur...![](https://i.imgur.com/hxGPJEY.png)

**Comment by guest4711** [comment]
I moved blitzmail.xml out of the way and everything looks fine again...

**Comment by grote** [comment]
Thanks for the info! Do you remember how you got into the situation? Did you manually play with the app's files or clear the cache?

**Comment by guest4711** [comment]
Once upon the time I run out of space. So I tested an app which cleans some unnecessary files, e.g. caches...

**Comment by grote** [comment]
The upcoming 0.7.1 release allows you to delete mails.
