### ISSUE TITLE
Mail is not sent when connection reestablished

### ISSUE THREAD

**Issue by Friptick** [grote/BlitzMail#45]
Perhaps a bug, perhaps not. To reproduce:

1. Write a note when offline. App says "No connection. Will be sent when a connection becomes available"
2. Go back online
3. Mail not sent! Need to "wake up" the app by tapping its icon

I have ensured app has (1) all permissions, (2) all notifications enabled, (3) is battery-unoptimized. Any ideas? From my limited knowledge of Android, seems like the app might need a permanent drawer notification to do this kind of background action, no?

In any case, this is still a great little app. Thanks @grote for your work.

Android 8. Current F-Droid version.

**Comment by grote** [comment]
No, it should work via WorkManager, but it might be a bit of time for the sending to get executed. Maybe wait some time while being online and see if it really never gets send.

**Comment by Friptick** [comment]
Thanks. After a bit of testing I can confirm that the mail is indeed sent in the end, i.e. 3-6 HOURS (!) after going back online. Whatever. It works. Closing.
