### ISSUE TITLE
 when there is no Internet connection only the message entered last will be sent

### ISSUE THREAD

**Issue by fbartels** [grote/BlitzMail#5]
Hi Torsten,

I today noticed a little error in BlitzMail that I want to report.

When there is currently no internet connection BlitzMail will present a dialogue where you can choose to retry. When putting new message into this "queue" older messages get lost.

Or put differently: when sending a new not the still waiting to be sent message is discarded.

Greetings and thanks for this otherwise great time safer Felix

**Comment by grote** [comment]
In the next version (0.6-beta2), BlitzMails will be send automatically, when the phone connects to the internet again.
