### ISSUE TITLE
Get rid of second launcher icon

### ISSUE THREAD

**Issue by ducalex** [grote/BlitzMail#52]
BlitzMail creates two icons in the launcher. BlitzNote to send notes and BlitzMail to configure the app.
I always get confused to which one to click when I want to send a note :(. It also wastes space (some launchers cannot hide/manage icons).

I propose removing the settings icon and instead add a settings button in the NoteActivity dialog.

I also propose opening the settings automatically if the server isn't configured, to avoid confusion.

My first idea was to replace the SAVE button with a CONFIG button. But to be less disruptive I think the title bar is a good place:
![BKV 1](https://user-images.githubusercontent.com/13711380/131578098-4303b5cc-6548-46e2-b07e-f2dbea5de86e.png)

If that is okay I will create a pull request with the small change.

_PS: In the screenshot I accidentally used string.app_name instead of string.note_name for title, I would fix that._

**Comment by grote** [comment]
Sorry, but I don't really like the idea of hiding the settings inside BlitzNote which I think of as an additional tool.

> I always get confused to which one to click when I want to send a note :(.

I dragged the BlitzNote icon to the home screen, so I can find it there quickly.

**Comment by ducalex** [comment]
That's fair enough, thanks for answering!
