### ISSUE TITLE
Listen for changes of network connectivity and send offline messages automatically

### ISSUE THREAD

**Issue by rgh36167** [grote/BlitzMail#7]
Hi,

I have encountered the following problem:

* go offline
* send  blitzmail #1 
* go online
* send blitzmail #2 

blitzmail #2 is immediately delivered, while blitzmail #1 still did not arrive. The notification that would allow me to resend it is gone after sending blitzmail #2 

Next I tried

* go offline
* send blitzmail #3 (fails with notification)
* go online
* go to notification - try again
* blitzmail #3 is delivered while blitzmail # 1 is still in nirvana

**Comment by grote** [comment]
[Monitor for Changes in Connectivity](https://developer.android.com/training/monitoring-device-state/connectivity-monitoring.html#MonitorChanges) from the Documentation might be the way to go here.
