### ISSUE TITLE
SMTP error 535 when debian-kit was launched before

### ISSUE THREAD

**Issue by Schwoggel** [grote/BlitzMail#8]
Hello,

This may not be an issue for BlitzMail at all but I wanted to report it anyway: I have the latest Blitzmail installed from f-droid and everything works fine until I start Debian via debian-kit [1]. Then, I'll get the error "Check SMTP settings: error 535 Authentication required".

So far, I only managed to fix this with a reboot until the next launch of debian-kit.

So, it is obviously something what debian-kit does that stops Blitzmail from working. But as other mail sending apps (e.g. K9) continue to work, I thought it may be something that can be solved in Blitzmail. 

Let me know if you need any further details and also if you have some hints for me to explain the problem  better to the Debian-kit developer.

Thanks!

Guido

[1] https://f-droid.org/repository/browse/?fdfilter=debian%20kit&fdid=org.dyndns.sven_ola.debian_kit

**Comment by grote** [comment]
Ok, no info in quite some time. Closing.
