### ISSUE TITLE
Can't use it to share images?

### ISSUE THREAD

**Issue by rgh36167** [grote/BlitzMail#9]
Hi,

when sharing images (from gallery or file manager) Blitzmail isn't shown in the list of choices to share (Motorola G).

Is it an error or simply missing functionality?

It would be really nice to have.

**Comment by leoauri** [comment]
+1 for this request! It's what I installed it for too..

**Comment by grote** [comment]
How to add intent filter for images: https://developer.android.com/training/basics/intents/filters.html
Handling the image intent: https://developer.android.com/training/sharing/receive.html
